### ISSUE TITLE
File nucleo.svg is missing

### ISSUE THREAD

**Issue by nazarlviv07** [app-generator/django-black-dashboard#7]
Hi,

In file static/assets/css/nucleo-icons.css you have a next line:   
`url('../fonts/nucleo.svg') format('svg');`

But actually in folder `static/assets/fonts` file `nucleo.svg` is missing

Could you please fix that bug? 

Thanks

**Comment by app-generator** [comment]
Hello! 

Sorry for the delay. The new AppSeed Service now manages the project and related issues:

https://app-generator.dev/ - Open-Source Platform.

Ty!
